### ISSUE TITLE
nlTopbar - ng-click

### ISSUE THREAD

**Issue by Aleksandern** [vincurekf/Native-like-Framework#19]
Hi Filip,
Thank you for nlFramework

I try to use ng-click like this but it doesn't work
`
  <div id="nlTopbar" class="depth z1">
    <div class="title" ng-click="doSomething()">
      {{ title }}
    </div>
  </div>
`
Why it doesn't work? I can I fix it somehow?

Thanks,
Alex

**Comment by Aleksandern** [comment]
It happens because of this line https://github.com/vincurekf/Native-like-Framework/blob/master/ng-nlFramework.scss#L212

why did you add pointer-events?

**Comment by vincurekf** [comment]
Hi Aleksandern,
thanks for using my framework! :)

To be honest, I don't recall the point of adding ```pointer-events: none``` to the ```title``` class, it could be something that i put there in early stage to disable text selection (not knowing that ```user-select: none``` exists.

Feel free to remove it, the code needs revision for small errors like this (I am not perfect :) ) but sadly i don't have the time now. Also, CSS is not one of my biggest strengths, so if you came across something else, and you think that it would make the framework better and more usable, please create pull request. :)
