### ISSUE TITLE
Support for iOS & Windows

### ISSUE THREAD

**Issue by vijay-vanecha** [vincurekf/Native-like-Framework#20]
Amazing plugin...

I have tested your example app on android. It's working very smooth. My phonegap app (i am not using ionic) need to support iOS and Windows devices. So i would like to know that, Is this plugin will work on iOS and Windows devices?

Thanks

**Comment by vincurekf** [comment]
Hi vijay,
this framework is just javascript manipulating DOM elements, 
so it should be working on all devices that your framework supports.

The only requirements for using this framework are:
   1. Your project must use Angular
   2. Your framework have to be Javascript + HTML

So as long as your framework works with javascript and uses Angular, you are good to go.
Hope this helped you :)

**Comment by vijay-vanecha** [comment]
Thanks for quick reply,

That's good. I am using Angular + JS + HTML. 
I will give it a try.

Thanks again.
