### ISSUE TITLE
Child views not triggering events ($ionicView.enter)

### ISSUE THREAD

**Issue by adamkearsley** [vincurekf/Native-like-Framework#24]
Hi.
Im using your example app and tying to trigger events in the child views.

```
exampleApp.controller('test', function($rootScope, $scope, $timeout) {
    $scope.$on('$ionicView.enter', function() {
          console.log('MYVIEW $ionicView.enter');
    });
});
```

It just doesn't get triggered?

**Comment by vincurekf** [comment]
Hi Adam,
I am not sure how this issue ties to nlFramework?

Sadly I don't know what is wrong there, 
but maybe this could help you: http://stackoverflow.com/a/14765954/1798395

I hope this helps.
