### ISSUE TITLE
Using framework with abstract states - Hammer issue

### ISSUE THREAD

**Issue by VBGWeb** [vincurekf/Native-like-Framework#25]
Hi,

We are developping an app with Ionic, and we wanted to use the sidemenu in a view different thant the index, so the nabvar wont appear on every view.
So we put the the menu in a sidemenu.html, with an abstract state.
The problem is that now we see the navbar, but the content inside appears empty (we see a blanck page), and we are getting this error on the hammer.min.js; Uncaught TypeError: Cannot read property 'addEventListener' of null.
Is there a way to implement your framework this way?

Here is an screenshot:
![image](https://cloud.githubusercontent.com/assets/17476877/16045409/9f84c4c0-321e-11e6-81f5-36c8f6065f96.png)

And here is the code:

Sidemenu.html:

`

<div id="nlActionButton" class="switch">
    <div class="action-button depth z1 option one" ng-click="toast.show({title: 'At the TOP!', position: 'top', timeout: 2500});">
        2
    </div>
    <div class="action-button depth z1 option two" ng-click="toast.show({title: 'At the BOTTOM!', timeout: 2500});">
        1
    </div>
    <div id="nlPlus" class="action-button depth z1 plus">
        <span>
    +
  </span>
    </div>
</div>

```
<!-- top nav bar -->
<ion-nav-bar>
    <div id="nlTopbar" class="depth z1">
        <div class="title">
            {{ title }}
        </div>
    </div>
</ion-nav-bar>
<!-- secondary menu -->
<div id="nlMenu" class="main">
    <div id="nlMenuContent">
        <!-- place your menu content here -->
        <ul>
            <li ng-click="toast.show({title:'Selected Share',timeout: 2500})">Share</li>
            <li ng-click="toast.show({title:'Selected Edit',timeout: 2500})">Edit</li>
            <li ng-click="toast.show({title:'Thanks!',timeout: 1000})">Hug someone</li>
        </ul>
    </div>
</div>
<!-- body of the menu drawer -->
```

<div id="nlDrawer">
    <div class="topbar drawer large">
        
        <div class="username">
            <strong>Conference</strong>
        </div>
    </div>
    <ion-list>
        <ion-item class="item-icon-left" href="#/sidemenu/agenda">
            <i class="icon ion-ios-calendar"></i> Agenda</a>
        </ion-item>
        <ion-item class="item-icon-left" href="#/muro">
            <i class="icon ion-ios-clock"></i> Muro</a>
        </ion-item>
        <ion-item class="item-icon-left" href="#/contacts">
            <i class="icon ion-ios-contact"></i> Participantes</a>
        </ion-item>
        <ion-item class="item-icon-left" href="#/oradores">
            <i class="icon ion-ios-people"></i> Expositores</a>
        </ion-item>
        <ion-item class="item-icon-left" href="#/sponsors/detail">
            <i class="icon ion-ios-star"></i> Sponsors</a>
        </ion-item>
    </ion-list>
    <ul class="nav">
        <div class="bottom">
            <li><a href="#login">Ingresar</a></li>
        </div>
    </ul>
</div>

<div id="nlContent">
    
    <div id="nlInner" ng-view="" class="page {{ title }}">
        <ion-nav-view name="content"></ion-nav-view>
    </div>
</div>

`

App.js
`$stateProvider

```
    .state('login', {
    url: '/login',
    templateUrl: 'templates/login.html',
    controller: 'loginCtrl'
})

.state('sidemenu', {
    url: '/sidemenu',
    abstract: true,
    templateUrl: 'templates/sidemenu.html',
})

.state('sidemenu.agenda', {
    url: '/agenda',
    views: {
        'content': {
            templateUrl: 'templates/tab-agenda.html',
            controller: 'AgendasCtrl as vm'
        }
    }
    });

// if none of the above states are matched, use this as the fallback
$urlRouterProvider.otherwise('/login');`
```

**Comment by vincurekf** [comment]
Hi Vanina,
one solution could be initializing the ```$nlDrawer``` in sidemenu controller.

And I noticed, you don't have ```#nlDrawer``` element in your ```sidemenu.html``` template, the ```#nlMenu``` is just the three dot menu in top right corner. But if this is the menu you want, then you need to initialize the ```$nlMenu``` inside of sidemenu controller. 

The problem probably is that you're trying to initialize without the DOM element.
I hope this helps.

**Comment by PremkumarAgrawal** [comment]
Hey @VBGWeb did you achived the goal to add side menu in your IONIC app, by using @vincurekf demo app in nlFramework.
