### ISSUE TITLE
Error: [$injector:modulerr] Failed to instantiate module nlFramework due to

### ISSUE THREAD

**Issue by ssyed-ahmed** [vincurekf/Native-like-Framework#28]
Hi,

I just tried the example code mentioned and I keep getting the following error:

> Uncaught Error: [$injector:modulerr] Failed to instantiate module loginappApp due to:
Error: [$injector:modulerr] Failed to instantiate module nlFramework due to:
Error: [$injector:nomod] Module 'nlFramework' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
http://errors.angularjs.org/1.6.2/$injector/nomod?p0=nlFramework
    at file:///android_asset/www/scripts/vendor.34c77dab.js:3:23662
    at file:///android_asset/www/scripts/vendor.34c77dab.js:4:2470
    at c (file:///android_asset/www/scripts/vendor.34c77dab.js:4:1932)
    at file:///android_asset/www/scripts/vendor.34c77dab.js:4:2244
    at file:///android_asset/www/scripts/vendor.34c77dab.js:4:12017
    at d (file:///android_asset/www/scripts/vendor.34c77dab.js:3:24094)
    at m (file:///android_asset/www/scripts/vendor.34c77dab.js:4:11865)
    at file:///android_asset/www/scripts/vendor.34c77dab.js:4:12034
    at d (file:///android_asset/www/scripts/vendor.34c77dab.js:3:24094)
    at m (file:///android_asset/www/scripts/vendor.34c77dab.js:4:11865)
http://errors.angularjs.org/1.6.2/$injector/modulerr?p0=nlFramework&p1=Error%3A%20%5B%24injector%3Anomod%5D%20Module%20'nlFramework'%20is%20not%20available!%20You%20either%20misspelled%20the%20module%20name%20or%20forgot%20to%20load%20it.%20If%20registering%20a%20module%20ensure%20that%20you%20specify%20the%20dependencies%20as%20the%20second%20argument.%0Ahttp%3A%2F%2Ferrors.angularjs.org%2F1.6.2%2F%24injector%2Fnomod%3Fp0%3DnlFramework%0A%20%20%20%20at%20file%3A%2F%2F%2Fandroid_asset%2Fwww%2Fscripts%2Fvendor.34c77dab.js%3A3%3A23662%0A%20%20%20%20at%20file%3A%2F%2F%2Fandroid_asset%2Fwww%2Fscripts%2Fvendor.34c77dab.js%3A4%3A2470%0A%20%20%20%20at%20c%20(file%3A%2F%2F%2Fandroid_asset%2Fwww%2Fscripts%2Fvendor.34c77dab.js%3A4%3A1932)%0A%20%20%20%20at%20file%3A%2F%2F%2Fandroid_asset%2Fwww%2Fscripts%2Fvendor.34c77dab.js%3A4%3A2244%0A%20%20%20%20at%20file%3A%2F%2F%2Fandroid_asset%2Fwww%2Fscripts%2Fvendor.34c77dab.js%3A4%3A12017%0A%20%20%20%20at%20d%20(file%3A%2F%2F%2Fandroid_asset%2Fwww%2Fscripts%2Fvendor.34c77dab.js%3A3%3A24094)%0A%20%20%20%20at%20m%20(file%3A%2F%2F%2Fandroid_asset%2Fwww%2Fscripts%2Fvendor.34c77dab.js%3A4%3A11865)%0A%20%20%20%20at%20file%3A%2F%2F%2Fandroid_asset%2Fwww%2Fscripts%2Fvendor.34c77dab.js%3A4%3A12034%0A%20%20%20%20at%20d%20(file%3A%2F%2F%2Fandroid_asset%2Fwww%2Fscripts%2Fvendor.34c77dab.js%3A3%3A24094)%0A%20%20%20%20at%20m%20(file%3A%2F%2F%2Fandroid_asset%2Fwww%2Fscripts%2Fvendor.34c77dab.js%3A4%3A11865)
    at file:///android_asset/www/scripts/vendor.34c77dab.js:3:23662
    at file:///android_asset/www/scripts/vendor.34c77dab.js:4:12294
    at d (file:///android_asset/www/scripts/vendor.34c77dab.js:3:24094)
    at m (file:///android_asset/www/scripts/vendor.34c77dab.js:4:11865)
    at file:///android_asset/www/scripts/vendor.34c77dab.js:4:12034
    at d (file:///android_asset/www/scripts/vendor.34c77dab.js:3:24094)
    at m (file:///android_asset/www/scripts/vendor.34c77dab.js:4:11865)
    at jb (file:///android_asset/www/scripts/vendor.34c77dab.js:4:13840)
    at g (file:///android_asset/www/scripts/vendor.34c77dab.js:3:31852)
    at ga (file:///android_asset/www/scripts/vendor.34c77dab.js:4:159)

> 
I double checked to see if there were any coding errors from my side, but could not find any. My dev environment is cordova with angularjs and bootstrap. The project structure was created using the yeoman scaffolding framework.

Any help regarding this would be greatly appreciated. 
Thanks,
Syed

**Comment by ssyed-ahmed** [comment]
Below is the index.html file under the app directory where I have included all the scripts and css styles needed by nlFramework. Am i missing something?

`<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
    <meta name="description" content="">
    <meta name="viewport" content="initial-scale=1, maximum-scale=1, user-scalable=no, width=device-width">
    
    
    
    <link rel="stylesheet" href="bower_components/bootstrap/dist/css/bootstrap.css" />
    
    
    
    <link rel="stylesheet" href="styles/main.css">
    <link rel="stylesheet" href="bower_components/components-font-awesome/css/font-awesome.css" />
    <link rel="stylesheet" href="bower_components/Native-like-Framework/dist/ng-nlFramework.css" />
    
    

  </head>
  <body ng-app="loginappApp">
    

    
    <my-header title="Home" subtitle=""></my-header>

    <div id="nlDrawer">

    </div>

    <div class="container-fluid">
      <div ng-view=""></div>
    </div>

    <div class="footer">

    </div>

    
     <script>
       !function(A,n,g,u,l,a,r){A.GoogleAnalyticsObject=l,A[l]=A[l]||function(){
       (A[l].q=A[l].q||[]).push(arguments)},A[l].l=+new Date,a=n.createElement(g),
       r=n.getElementsByTagName(g)[0],a.src=u,r.parentNode.insertBefore(a,r)
       }(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

       ga('create', 'UA-XXXXX-X');
       ga('send', 'pageview');
    </script>


    
    
    <script src="bower_components/jquery/dist/jquery.js"></script>
    <script src="bower_components/angular/angular.js"></script>
    <script src="bower_components/bootstrap/dist/js/bootstrap.js"></script>
    <script src="bower_components/angular-animate/angular-animate.js"></script>
    <script src="bower_components/angular-cookies/angular-cookies.js"></script>
    <script src="bower_components/angular-resource/angular-resource.js"></script>
    <script src="bower_components/angular-route/angular-route.js"></script>
    <script src="bower_components/angular-sanitize/angular-sanitize.js"></script>
    <script src="bower_components/angular-touch/angular-touch.js"></script>
    
    

        
        <script src="bower_components/hammerjs/hammer.js"></script>
        <script src="bower_components/Native-like-Framework/dist/ng-nlFramework.js"></script>
        <script src="scripts/app.js"></script>

        
        <script src="scripts/app.constants.js"></script>
        <script src="scripts/controllers/main.js"></script>
        <script src="scripts/controllers/about.js"></script>
        <script src="scripts/services/cordova.js"></script>
        <script src="scripts/services/LoginService.js"></script>
        <script src="scripts/directives/header.js"></script>
        <script src="scripts/directives/login-loading.js"></script>
        <script src="scripts/controllers/LoginController.js"></script>
        
</body>
</html>
`

**Comment by vincurekf** [comment]
Hi @ssyed-ahmed 
can you please show me how the code where you call the nlFramework looks, the ```LoginController.js```?
And are you sure that the nlFrameworks code is being included?
You can try to move the ```ng-nlFramework.js``` to your ```scripts``` directory and then load that file.

I can't help You more right now.

**Comment by ssyed-ahmed** [comment]
Hi @vincurekf 

There was an environment setup issue in my project. After starting a new project and installing all the required libraries afresh, it worked :)
Thanks for your time.
